# The version is to help determine which version this config is. Please don't modify this value.
version: "@version@"

# Print additional information in the console. Useful for figuring out errors and issues.
debug: false

general:
    # The max amount of new lines a user is allowed to enter in inputtable placeholders.
    new-lines: 4
    date-format: "MM/dd/yyyy HH:mm:ss"

database:
    # Types are MYSQL and H2.
    type: "H2"
    autosave: "5 minutes"
    # Table name configuration for databases.
    player-table: "Players"
    mysql:
        user: "root"
        address: "localhost"
        password: "password"
        name: "example"
